<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="largo84.20170410113547.3"><vh>@settings</vh>
<v t="largo84.20170410113629.1"><vh>@data abbreviations</vh>
<v t="largo84.20170410113721.1"><vh>LaTex (General)</vh>
<v t="largo84.20170410113721.2"><vh>Lists</vh></v>
<v t="largo84.20170410113721.5"><vh>Text formatting</vh></v>
<v t="largo84.20170410113801.1"><vh>Others</vh></v>
</v>
<v t="largo84.20170410114714.1"><vh>LaTex (Exam Class)</vh>
<v t="largo84.20170410113721.3"><vh>Questions and Parts</vh></v>
<v t="largo84.20170410113721.4"><vh>Solution blocks</vh></v>
<v t="largo84.20170410114857.1"><vh>Others</vh></v>
</v>
</v>
<v t="largo84.20170410120436.1"><vh>@outline-data tree-abbreviations</vh>
<v t="largo84.20170410120436.22"><vh>sec;;</vh>
<v t="largo84.20170410120436.23"><vh>&lt;|Section Name|&gt;</vh></v>
</v>
<v t="largo84.20170410120436.24"><vh>ssec;;</vh>
<v t="largo84.20170410120436.25"><vh>&lt;|SubSection Name|&gt;</vh></v>
</v>
<v t="largo84.20170410120436.26"><vh>sssec;;</vh>
<v t="largo84.20170410120436.27"><vh>&lt;|SubSubSection Name|&gt;</vh></v>
</v>
<v t="largo84.20170410120957.1"><vh>par;;</vh>
<v t="largo84.20170410120957.2"><vh>&lt;|Paragraph Title|&gt;</vh></v>
</v>
<v t="largo84.20170410120436.28"><vh>part;;</vh>
<v t="largo84.20170410120436.29"><vh>&lt;|Part Name|&gt;</vh></v>
</v>
<v t="largo84.20170410120436.32"><vh>texdoc;;</vh>
<v t="largo84.20170410120436.33"><vh>@@file &lt;|UDI|&gt; &lt;|Document|&gt;.tex</vh>
<v t="largo84.20170410120436.52"><vh>&lt;&lt; Paths &gt;&gt;</vh></v>
<v t="largo84.20170410120436.53"><vh>&lt;&lt; Project Variables &gt;&gt;</vh></v>
<v t="largo84.20170410120436.54"><vh>&lt;&lt; Document Variables &gt;&gt;</vh>
<v t="largo84.20170410120436.55"><vh>&lt;&lt; Fonts &gt;&gt;</vh></v>
<v t="largo84.20170410120436.56"><vh>&lt;&lt; Packages &gt;&gt;</vh></v>
<v t="largo84.20170410120436.57"><vh>&lt;&lt; Definitions &gt;&gt;</vh>
<v t="largo84.20170410120436.58"><vh>Sizes</vh></v>
<v t="largo84.20170410120436.61"><vh>Exam Class Definitions</vh></v>
</v>
<v t="largo84.20170410120436.63"><vh>&lt;&lt; Meta Info &gt;&gt;</vh></v>
<v t="largo84.20170410120436.64"><vh>&lt;&lt; Page Headers and Footers &gt;&gt;</vh>
<v t="largo84.20170410120436.65"><vh>&lt;&lt; Page Style &gt;&gt;</vh></v>
<v t="largo84.20170410120436.66"><vh>&lt;&lt; Header &gt;&gt;</vh></v>
<v t="largo84.20170410120436.67"><vh>&lt;&lt; Footer &gt;&gt;</vh></v>
</v>
</v>
</v>
</v>
<v t="largo84.20170410120436.50"><vh>texmanual;;</vh>
<v t="largo84.20170410120436.51"><vh>@@file &lt;|UDI|&gt; &lt;|Training Manual|&gt;.tex</vh>
<v t="largo84.20170410120436.52"></v>
<v t="largo84.20170410120436.53"></v>
<v t="largo84.20170410120436.54"></v>
<v t="largo84.20170410120436.68"><vh>&lt;&lt; Title Page &gt;&gt;</vh></v>
<v t="largo84.20170410120436.69"><vh>&lt;&lt; Document Body &gt;&gt;</vh></v>
</v>
</v>
</v>
</v>
<v t="largo84.20170410123207.1"><vh>Use Cases</vh></v>
<v t="largo84.20170410123325.1"><vh>Workflow Overview</vh></v>
<v t="largo84.20170410123813.1"><vh>Workflow Notes and Shortcuts</vh></v>
<v t="largo84.20170410124219.1"><vh>Software Needed</vh></v>
<v t="largo84.20170410124311.1"><vh>Document Example</vh>
<v t="largo84.20170410124440.1"><vh>Resources</vh>
<v t="largo84.20170410124929.1"><vh>(XXX-H120) Reusable Content</vh>
<v t="largo84.20170410124935.1" descendentVnodeUnknownAttributes="7d710058010000003071017d7102580500000069636f6e7371035d71047d710528580a00000076697375616c49636f6e710658010000003171075807000000796f666673657471084b005807000000786f666673657471094b02580400000066696c65710a583d000000443a2f53796e6365642f676974687562207265706f732f6c656f2f6c656f2f49636f6e732f66696c655f69636f6e732f66696c655f66696c652e706e67710b580400000074797065710c680a58020000006f6e710d5805000000766e6f6465710e580700000072656c50617468710f581800000066696c655f69636f6e732f66696c655f66696c652e706e677110580500000077686572657111580e0000006265666f7265486561646c696e65711258040000007870616471134b01756173732e"><vh>@file Reusable Content.txi</vh></v>
</v>
</v>
<v t="largo84.20170410125918.1"><vh>Smith Grocery Company (the client)</vh>
<v t="largo84.20170410130109.2" descendentVnodeUnknownAttributes="7d710058010000003071017d7102580500000069636f6e7371035d71047d710528580a00000076697375616c49636f6e710658010000003171075807000000796f666673657471084b005807000000786f666673657471094b02580400000066696c65710a583d000000443a2f53796e6365642f676974687562207265706f732f6c656f2f6c656f2f49636f6e732f66696c655f69636f6e732f66696c655f66696c652e706e67710b580400000074797065710c680a58020000006f6e710d5805000000766e6f6465710e580700000072656c50617468710f581800000066696c655f69636f6e732f66696c655f66696c652e706e677110580500000077686572657111580e0000006265666f7265486561646c696e65711258040000007870616471134b01756173732e"><vh>@file SGC-H120 Reusable Content.tex</vh></v>
<v t="largo84.20170410131222.2" descendentVnodeUnknownAttributes="7d710058010000003071017d7102580500000069636f6e7371035d71047d710528580a00000076697375616c49636f6e710658010000003171075807000000796f666673657471084b005807000000786f666673657471094b02580400000066696c65710a583d000000443a2f53796e6365642f676974687562207265706f732f6c656f2f6c656f2f49636f6e732f66696c655f69636f6e732f66696c655f66696c652e706e67710b580400000074797065710c680a58020000006f6e710d5805000000766e6f6465710e580700000072656c50617468710f581800000066696c655f69636f6e732f66696c655f66696c652e706e677110580500000077686572657111580e0000006265666f7265486561646c696e65711258040000007870616471134b01756173732e"><vh>@file SGC-M110 Training Manual.tex</vh></v>
<v t="largo84.20190218170416.7"><vh>@file Client Variables.txi</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="largo84.20170410113547.3"></t>
<t tx="largo84.20170410113629.1"># Comments lines (lines starting with '#') are ignored.
# Non-comment lines should have the form::
#
#    name=definition

# Definitions in @data abbreviation nodes override definitions in @data
# global-abbreviation nodes. Typically you would define @data abbreviation nodes
# in myLeoSettings.leo

</t>
<t tx="largo84.20170410113721.1"></t>
<t tx="largo84.20170410113721.2">enum;;=\begin{enumerate}
\:    \item &lt;|Item1|&gt;
\:    \item &lt;|Item2|&gt;
\:\end{enumerate}
\:

itz;;=\begin{itemize}
\:    \item &lt;|Item1|&gt;
\:    \item &lt;|Item|&gt;
\:\end{itemize}
\:

desc;;=\begin{quote} %Indents description block (optional).
\:  \begin{description}
\:      \item[&lt;|Title1|&gt;] &lt;|Description1|&gt;
\:      \item[&lt;|Title2|&gt;] &lt;|Description2|&gt;
\:  \end{description}
\:\end{quote}
\:

item;;=\item &lt;|Item|&gt;
itemd;;=\item[&lt;|Title|&gt;] &lt;|Description|&gt;
</t>
<t tx="largo84.20170410113721.3">qqs;;=\begin{questions}
\:    \question[&lt;|Points|&gt;] \label{&lt;|Label-Text|&gt;} &lt;|Question-Text|&gt;
\:\end{questions}
</t>
<t tx="largo84.20170410113721.4"># The following abbreviations create a note-taking block filled with horizontal lines on the student version and facilitator notes for the teacher version.
# The number of lines is determined by the size of the block ranging from tiny (2 lines) to huge (6 lines).
# These are defined using the following global commands:
# \newcommand{\tinysbh}{.5in} %\sbh = solution box height (.5)=2 lines
# \newcommand{\smallsbh}{.75in} %\sbh = solution box height (.75)=3 lines
# \newcommand{\mediumsbh}{1in} %\sbh = solution box height (1)=4 lines
# \newcommand{\largesbh}{1.25in} %\sbh = solution box height (1.25)=5 lines
# \newcommand{\hugesbh}{1.5in} %\sbh = solution box height (1.5)=6 lines

sbht;;=\begin{solutionorlines}[\tinysbh]
\:
\:    &lt;|Facilitator Notes|&gt;
\:\end{solutionorlines}

sbhs;;=\begin{solutionorlines}[\smallsbh]
\:
\:    &lt;|Facilitator Notes|&gt;
\:\end{solutionorlines}

sbhm;;=\begin{solutionorlines}[\mediumsbh]
\:
\:    &lt;|Facilitator Notes|&gt;
\:\end{solutionorlines}

sbhl;;=\begin{solutionorlines}[\largesbh]
\:
\:    &lt;|Facilitator Notes|&gt;
\:\end{solutionorlines}

sbhh;;=\begin{solutionorlines}[\hugesbh]
\:
\:    &lt;|Facilitator Notes|&gt;
\:\end{solutionorlines}
</t>
<t tx="largo84.20170410113721.5">supermac;;=M\textsuperscript{&lt;|ac|&gt;}&lt;|Name|&gt; %Useful for names like MacDonald or McGinnis.

super;;=\textsuperscript{&lt;|th|&gt;} %Useful for constructs such as 7th or 2nd.

red;;=\textcolor{red}{&lt;|Red-Text|&gt;}
blue;;=\textcolor{blue}{&lt;|Blue-Text|&gt;}

bld;;=\textbf{&lt;|BoldText|&gt;}
emph;;=\emph{&lt;|EmphasizedText|&gt;}
</t>
<t tx="largo84.20170410113801.1">cp;;=\clearpage
\:

box;;=\begin{center}
\:  \fbox{\fbox{\parbox{\textwidth}{&lt;|Instructions placed inside a framed box.|&gt;}}}
\:\end{center}

par;;=\paragraph{&lt;|Paragraph-Title|&gt;} &lt;|Paragraph-Text|&gt;</t>
<t tx="largo84.20170410114714.1"># These LaTex constructs are unique to the exam document class and will not work in other document classes.
</t>
<t tx="largo84.20170410114857.1"># The following construct makes it easy to create different content depending on which output version is selected (facilitator or student).
# This is easily determined in the document preamble as in:
# \documentclass[addpoints,12pt,answers]{exam} for facilitator version
# \documentclass[addpoints,12pt]{exam} for student version

ifp;;=\ifprintanswers %Print for Facilitator only.
\:  &lt;|Facilitator-Text|&gt;
\:\else %Print for Students only.
\:  &lt;|Student-Text|&gt;
\:\fi
\:</t>
<t tx="largo84.20170410120436.1">sec;;
ssec;;
sssec;;
part;;
texdoc;;
texmanual;;
</t>
<t tx="largo84.20170410120436.22"># Creates a child node for a LaTex section.</t>
<t tx="largo84.20170410120436.23">\section[&lt;|Index-Title|&gt;]{&lt;|Section-Name|&gt;}
\label{sec:&lt;|Label-Text|&gt;}

\input{"&lt;|Section File Name|&gt;.txi"} %Inserts external content file.</t>
<t tx="largo84.20170410120436.24"># Creates a child node for a LaTex subsection.</t>
<t tx="largo84.20170410120436.25">\subsection&lt;|Index-Title|&gt;{&lt;|Subsection-Name|&gt;}
\label{ssec:&lt;|Label-Text|&gt;}

\input{"&lt;|SubSection File Name|&gt;.txi"} %Inserts external content file.
</t>
<t tx="largo84.20170410120436.26"># Creates a child node for a LaTex subsubsection.</t>
<t tx="largo84.20170410120436.27">\subsubsection&lt;|Index-Title|&gt;{&lt;|Subsubsection Name|&gt;}
\label{sssec:&lt;|Label-Text|&gt;}

\input{"&lt;|SubSubSection File Name|&gt;.txi"} %Inserts external content file.
</t>
<t tx="largo84.20170410120436.28"># Creates a child node for LaTex part (doesn't work for every document class).</t>
<t tx="largo84.20170410120436.29">\part&lt;|Index-Title|&gt;{&lt;|Part-Name|&gt;}
\label{pt:&lt;|Label-Text|&gt;}

\input{"&lt;|Part File Name|&gt;.txi"} %Inserts external content file.
</t>
<t tx="largo84.20170410120436.32"># Creates a new document 'shell' with variables.
# Use this mostly for student versions only needing one (or a few) content files.</t>
<t tx="largo84.20170410120436.33">@language tex
\documentclass[addpoints,12pt&lt;|,answers|&gt;]{exam} %Use `,answers` for Facilitator and delete for Student version.
&lt;&lt; Paths &gt;&gt;
&lt;&lt; Project Variables &gt;&gt;
&lt;&lt; Document Variables &gt;&gt;

\begin{document}
    \input{"\ResourcePath &lt;|somefile|&gt;.txi"}
\end{document}
</t>
<t tx="largo84.20170410120436.50"># Creates a new document 'shell' with variables (eg. UDI is the Unique Document Identifier assigned to the specific version of this document).
# Use this mostly for facilitatir versions that will contain multiple content files.</t>
<t tx="largo84.20170410120436.51">@language tex
\documentclass[addpoints,12pt&lt;|,answers|&gt;]{exam} %Use `,answers` for Facilitator and delete for Student version.
&lt;&lt; Paths &gt;&gt;
&lt;&lt; Project Variables &gt;&gt;
&lt;&lt; Document Variables &gt;&gt;

\begin{document}
    &lt;&lt; Title Page &gt;&gt;
    &lt;&lt; Document Body &gt;&gt;
\end{document}
</t>
<t tx="largo84.20170410120436.52">\newcommand{\MainPath}{C:/Main\space Document\space Path/}

\newcommand{\TemplatePath}{\MainPath Templates/LaTex\space Documents/}
\newcommand{\AgreementPath}{\MainPath Templates/Agreements/}
\newcommand{\ResourcePath}{\MainPath Resources/}
</t>
<t tx="largo84.20170410120436.53">\input{"Client\space Variables.txi"} % Sets the client name and other related client-specific commands.
\newcommand{\theSchoolShort}{XYZ} % The short name of the class. Only change this line to reflect the correct school name.
\newcommand{\theCourseShort}{ABC} % The short name of the online course. Only change this line to reflect the correct course name.
</t>
<t tx="largo84.20170410120436.54">\newcommand{\UDI}{&lt;|Prefix|&gt;-&lt;|M|&gt;&lt;|123|&gt;} % Unique Document Identifier (F=Form, H=Handout, Q=Test, Quiz or Exam, M=Manual, W=Worksheet, A=Article, C=Contract, S=Script)
\newcommand{\docTitle}{&lt;|Document Title|&gt;} %  ...to show up in the header
\newcommand{\REV}{&lt;|17.04.10|&gt;} % Revision number (date), used in combination w/ the UDI as in: FSS-Q101(15.06.08)

\newcommand{\keywords}{&lt;|sales|&gt; &lt;|training|&gt; &lt;|handout|&gt; \theSchoolShort} %This information will fill in the meta info for PDF creation.

&lt;&lt; Fonts &gt;&gt;
&lt;&lt; Packages &gt;&gt;
&lt;&lt; Definitions &gt;&gt;
&lt;&lt; Meta Info &gt;&gt;
&lt;&lt; Page Headers and Footers &gt;&gt;
</t>
<t tx="largo84.20170410120436.55">@
Use this section to define document fonts.
@c

\usepackage[T1]{fontenc}
\usepackage{gentium} %Gentium

%\usepackage{quattrocento} %Quattrocento
%\usepackage{mathpazo} %Palatino
%\usepackage{lmodern} %Latin Modern
%\usepackage{cm-super} %Computer Modern Super (don't use, it may not be installed.)

</t>
<t tx="largo84.20170410120436.56">\usepackage{color}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{stmaryrd}
\usepackage{ifsym}
\usepackage{MnSymbol}
\usepackage{textcomp}
\usepackage{verbatim}
\usepackage{wasysym}
\usepackage{ifpdf} %added to support checking to see if pdflatex is used
\usepackage{hyperref}
\usepackage{graphicx,color} % Necessary for adding images and other graphics.
\usepackage{wrapfig} % This allows for wrapping text around images and figures.
\graphicspath{C:/Images/} %Define path(s) to image files.
\usepackage{array} %Extends the tabular environment
\usepackage{xfrac} %Split level fractions \sfrac{&lt;num&gt;}{&lt;den&gt;}
\usepackage[utf8]{inputenc} %Allows direct input of unicode characters, such as café.

</t>
<t tx="largo84.20170410120436.57">@others

</t>
<t tx="largo84.20170410120436.58">\setlength\answerlinelength{3in}
\setlength\answerskip{0.1in}
%\setlength\parindent{0in}
%\setlength\parskip{1.5ex}
%\setlength\parskip{6pt}
\newcommand{\tinysbh}{.5in} %\sbh = solution box height (.5)=2 lines
\newcommand{\smallsbh}{.75in} %\sbh = solution box height (.75)=3 lines
\newcommand{\mediumsbh}{1in} %\sbh = solution box height (1)=4 lines
\newcommand{\largesbh}{1.25in} %\sbh = solution box height (1.25)=5 lines
\newcommand{\hugesbh}{1.5in} %\sbh = solution box height (1.5)=6 lines
</t>
<t tx="largo84.20170410120436.61">\renewcommand{\solutiontitle}{\noindent{Facilitation Notes: }}

\CorrectChoiceEmphasis{\color{red} \itshape}
\SolutionEmphasis{\color{red} \itshape}
\unframedsolutions % prevents solutions from being displayed inside an \fbox

\newcommand\resetcheckboxchar{\checkboxchar{$\bigcirc$}}
\resetcheckboxchar %Sets default display characters for check boxes.

\newcommand\resetcheckedchar{\checkedchar{$\varoast$}} %varoast is a circle surroundeing an asterisk.
\resetcheckedchar %Sets default display characters for correct choices on answer keys.

\newcommand\truefalsecheckboxchar{\checkboxchar{\textbf{T or F}}} %Sets the default characters for True/False questions.
\newcommand\truecheckedchar{\checkedchar{\textbf{T}}} %Sets the default character for True statements on answer keys.
\newcommand\falsecheckboxchar{\checkboxchar{\textbf{F}}} %Sets the default character for False statements on answer keys.

\checkboxchar{$\bigcirc$} %This displays an empty circle.
\checkedchar{$\varoast$} %This displays a circle filled with an asterisk.
</t>
<t tx="largo84.20170410120436.63">@
Include at the beginning of all 'Grafton' and DDI documents after document variables and global definitions.
@c
\hypersetup{
  pdftitle={\theSchool : \docTitle},
  pdfauthor={Author Name},
  pdfsubject={\theSchool : \docTitle},
  pdfkeywords={\keywords },
  pdfstartview={Fit},
  pdfpagelayout={SinglePage},
  pdfdisplaydoctitle={True},
  pdfpagemode={UseNone} %UseNone for no sidebar, UseOutlines to show bookmarks
}

\title{\theSchool : \docTitle}
\author{Author Name}
\date{Revised: \today}
</t>
<t tx="largo84.20170410120436.64">@
Include this section as the last preamble before \begin{document} for all documents.
If there's a mismatch between this version and the 'global' version, use:
\input{"\TemplatePath Page\space Headers-Footers.txi"}
@c
&lt;&lt; Page Style &gt;&gt;
&lt;&lt; Header &gt;&gt;
&lt;&lt; Footer &gt;&gt;
</t>
<t tx="largo84.20170410120436.65">\pagestyle{headandfoot} 
% \runningheadrule % Use this one to skip a rule on the first page.
\headrule
\footrule
</t>
<t tx="largo84.20170410120436.66">\header
    {} %Left side header
    {\bfseries \large \docTitle} % Center header
    {} %Right side header
</t>
<t tx="largo84.20170410120436.67">\footer
    %Left
    {\UDI (\REV )\\ \ifprintanswers \textcolor{red}{Facilitator Notes} \else \fi} % Left side includes the document identifier and revision date.
    %Center
    {\bfseries Footer Text \ifthenelse{\equal{\theSchoolShort}{XYZ}}{}{\\ \theSchool}} % Center includes `Footer Text` and the specific course name (if other than just XYZ).
    %Right
    {Page \thepage{} of \numpages} % Right side includes the paging information.
</t>
<t tx="largo84.20170410120436.68">@
Add the following title page if desired. Otherwise, comment it out.
@c

\makeatletter
\@addtoreset{section}{part} % This should reset the section counter when the part counter changes.
\makeatother

\pointsinrightmargin
\maketitle
\begin{center} %Add company logo.
    \includegraphics[width=0.5\textwidth]{logo.png}
\end{center}
\clearpage
\tableofcontents
\clearpage


</t>
<t tx="largo84.20170410120436.69">\input{"\ResourcePath &lt;|somefile|&gt;.txi"}</t>
<t tx="largo84.20170410120957.1"># Creates a child node for a LaTex paragraph.</t>
<t tx="largo84.20170410120957.2">\paragraph{&lt;|Paragraph-Title|&gt;} &lt;|Paragraph-Text|&gt;
</t>
<t tx="largo84.20170410123207.1">* I teach a variety of classes in a business environment and need handouts, teaching aids, worksheets and training manuals that are specifically customized for each client.
* These documents are easier to manage, print and protect using standard PDFs.
* Content files (content.txi) are easily reusable for multiple clients.
* Both student-specific and teacher-specific content can be included in the content files, differentiated by the output shell version.</t>
<t tx="largo84.20170410123325.1">1. Document content comes from a primary resource directory arranged by topic (not client specific).
2. Create a `Resources.leo` file to help keep that directory organized.
3. All of the content files are written in LaTex (I use a .txi file extension of my own invention to indicate the file is an 'input' file only, not the main output file which uses .tex).
4. Create a `Client.leo` file for each client in their own directory to organize work specific to each client.
5. For each document needed for a client project, create a `Document.tex` file from a standard template and change the document properties as needed for the specific client, project and document.
6. The `Document.tex` file acts as the presentation 'shell' for the document.
    1. Simply add \input{"\ResourcePath Content.txi"} after the \begin{document} statement (\ResourcePath is a shortcut command to the location of the content resource).
    2. This shell determines such things as the document title, document type, client name, header/footer information and revision date.
7. In Windows, use TeXNicCenter to process (typeset) the `Document.tex` file to create PDF output. (Don't use TeXNicCenter for editing, only file processing).
</t>
<t tx="largo84.20170410123813.1">1. Years ago, I discovered the incredible exam class for LaTex and now use it almost exclusively.
    * It makes it much easier to create student and teacher versions of the same content (eg. handout for students and training manual with speaking notes for the teacher).
    * http://www-math.mit.edu/~psh/exam/examdoc.pdf
2. I use the new @outline-data tree-abbreviations in Leo to create each new `Document.tex` file from a template with variables (very cool!)
    * unl://#@settings:0--&gt;@outline-data%20tree-abbreviations:1--&gt;texdoc``:5
3. I created many @data abbreviations in Leo to speed up typing of standard LaTex structures.
    * unl://#@settings:0--&gt;@data%20abbreviations:0
4. All document content stays in the Resources directory and only 'shell' documents are in the client directories.
    * These shell documents allow for client-specific information to be added to the headers, footers and in some cases as variables inside the content area itself (using \theClient variable that I define).
</t>
<t tx="largo84.20170410124219.1">* Leo (of course, and its dependencies).
* MiKTex for the LaTeX distribution and package management (I have it set to auto-update as needed).
* TeXNicCenter for processing (typesetting) to PDF output.</t>
<t tx="largo84.20170410124311.1">@language tex

This example shows a content file (Resources)  and two document 'shells' (a student handout and a training manual) in the client directory.
</t>
<t tx="largo84.20170410124440.1">@path Resources/
</t>
<t tx="largo84.20170410124929.1">This content may be used for a variety of clients. For example, Smith Grocery Company:
Client Abbreviation: SGC
\newcommand{\theClient}{Smith Grocery Company} %Defined in the document preamble.
The document prepared for SGC will have a Unique Document Identifier (UDI) of SGC-H120 and a revision date in the footer as in:
    SGC-H120 (17.04.10)
</t>
<t tx="largo84.20170410125918.1">@path Client/
The following files were created with the @outline-data tree-abbreviations `texdoc` and `texmanual` abbreviations.
</t>
</tnodes>
</leo_file>
